/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": {
                        /** Format: uuid */
                        taskItemId?: string;
                    } & {
                        files?: components["schemas"]["IFormFile"][];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SubmissionDto"];
                        "application/json": components["schemas"]["SubmissionDto"];
                        "text/json": components["schemas"]["SubmissionDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submissions/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SubmissionStatusDto"];
                        "application/json": components["schemas"]["SubmissionStatusDto"];
                        "text/json": components["schemas"]["SubmissionStatusDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submissions/{id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EvaluationResultDto"];
                        "application/json": components["schemas"]["EvaluationResultDto"];
                        "text/json": components["schemas"]["EvaluationResultDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TaskCategoryDto"][];
                        "application/json": components["schemas"]["TaskCategoryDto"][];
                        "text/json": components["schemas"]["TaskCategoryDto"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TaskItemDto"];
                        "application/json": components["schemas"]["TaskItemDto"];
                        "text/json": components["schemas"]["TaskItemDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminLoginDto"];
                    "text/json": components["schemas"]["AdminLoginDto"];
                    "application/*+json": components["schemas"]["AdminLoginDto"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AdminSessionDto"];
                        "application/json": components["schemas"]["AdminSessionDto"];
                        "text/json": components["schemas"]["AdminSessionDto"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TaskCategoryDto"][];
                        "application/json": components["schemas"]["TaskCategoryDto"][];
                        "text/json": components["schemas"]["TaskCategoryDto"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTaskCategoryDto"];
                    "text/json": components["schemas"]["CreateTaskCategoryDto"];
                    "application/*+json": components["schemas"]["CreateTaskCategoryDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TaskCategoryDto"];
                        "application/json": components["schemas"]["TaskCategoryDto"];
                        "text/json": components["schemas"]["TaskCategoryDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateTaskCategoryDto"];
                    "text/json": components["schemas"]["UpdateTaskCategoryDto"];
                    "application/*+json": components["schemas"]["UpdateTaskCategoryDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TaskCategoryDto"];
                        "application/json": components["schemas"]["TaskCategoryDto"];
                        "text/json": components["schemas"]["TaskCategoryDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/categories/{id}/visibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["VisibilityStateDto"];
                        "application/json": components["schemas"]["VisibilityStateDto"];
                        "text/json": components["schemas"]["VisibilityStateDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/admin/tasks/{taskItemId}/weights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    taskItemId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TaskCategoryWeightDto"][];
                        "application/json": components["schemas"]["TaskCategoryWeightDto"][];
                        "text/json": components["schemas"]["TaskCategoryWeightDto"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    taskItemId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SaveTaskCategoryWeightsDto"];
                    "text/json": components["schemas"]["SaveTaskCategoryWeightsDto"];
                    "application/*+json": components["schemas"]["SaveTaskCategoryWeightsDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TaskCategoryWeightDto"][];
                        "application/json": components["schemas"]["TaskCategoryWeightDto"][];
                        "text/json": components["schemas"]["TaskCategoryWeightDto"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TaskItemDto"][];
                        "application/json": components["schemas"]["TaskItemDto"][];
                        "text/json": components["schemas"]["TaskItemDto"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTaskItemDto"];
                    "text/json": components["schemas"]["CreateTaskItemDto"];
                    "application/*+json": components["schemas"]["CreateTaskItemDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TaskItemDto"];
                        "application/json": components["schemas"]["TaskItemDto"];
                        "text/json": components["schemas"]["TaskItemDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TaskItemDto"];
                        "application/json": components["schemas"]["TaskItemDto"];
                        "text/json": components["schemas"]["TaskItemDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateTaskItemDto"];
                    "text/json": components["schemas"]["UpdateTaskItemDto"];
                    "application/*+json": components["schemas"]["UpdateTaskItemDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TaskItemDto"];
                        "application/json": components["schemas"]["TaskItemDto"];
                        "text/json": components["schemas"]["TaskItemDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/tasks/{id}/visibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["VisibilityStateDto"];
                        "application/json": components["schemas"]["VisibilityStateDto"];
                        "text/json": components["schemas"]["VisibilityStateDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/admin/tasks/{taskItemId}/tests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    taskItemId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TaskTestDto"][];
                        "application/json": components["schemas"]["TaskTestDto"][];
                        "text/json": components["schemas"]["TaskTestDto"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    taskItemId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SaveTaskTestsDto"];
                    "text/json": components["schemas"]["SaveTaskTestsDto"];
                    "application/*+json": components["schemas"]["SaveTaskTestsDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TaskTestDto"][];
                        "application/json": components["schemas"]["TaskTestDto"][];
                        "text/json": components["schemas"]["TaskTestDto"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    taskItemId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTaskTestDto"];
                    "text/json": components["schemas"]["CreateTaskTestDto"];
                    "application/*+json": components["schemas"]["CreateTaskTestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TaskTestDto"];
                        "application/json": components["schemas"]["TaskTestDto"];
                        "text/json": components["schemas"]["TaskTestDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/tasks/{taskItemId}/tests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    taskItemId: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateTaskTestDto"];
                    "text/json": components["schemas"]["UpdateTaskTestDto"];
                    "application/*+json": components["schemas"]["UpdateTaskTestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TaskTestDto"];
                        "application/json": components["schemas"]["TaskTestDto"];
                        "text/json": components["schemas"]["TaskTestDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    taskItemId: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/tasks/{taskItemId}/unittests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    taskItemId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TaskUnitTestFileDto"][];
                        "application/json": components["schemas"]["TaskUnitTestFileDto"][];
                        "text/json": components["schemas"]["TaskUnitTestFileDto"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    taskItemId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SaveTaskUnitTestFilesDto"];
                    "text/json": components["schemas"]["SaveTaskUnitTestFilesDto"];
                    "application/*+json": components["schemas"]["SaveTaskUnitTestFilesDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TaskUnitTestFileDto"][];
                        "application/json": components["schemas"]["TaskUnitTestFileDto"][];
                        "text/json": components["schemas"]["TaskUnitTestFileDto"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    taskItemId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTaskUnitTestFileDto"];
                    "text/json": components["schemas"]["CreateTaskUnitTestFileDto"];
                    "application/*+json": components["schemas"]["CreateTaskUnitTestFileDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TaskUnitTestFileDto"];
                        "application/json": components["schemas"]["TaskUnitTestFileDto"];
                        "text/json": components["schemas"]["TaskUnitTestFileDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/tasks/{taskItemId}/unittests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    taskItemId: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateTaskUnitTestFileDto"];
                    "text/json": components["schemas"]["UpdateTaskUnitTestFileDto"];
                    "application/*+json": components["schemas"]["UpdateTaskUnitTestFileDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TaskUnitTestFileDto"];
                        "application/json": components["schemas"]["TaskUnitTestFileDto"];
                        "text/json": components["schemas"]["TaskUnitTestFileDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    taskItemId: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AdminLoginDto: {
            password: string;
        };
        AdminSessionDto: {
            isAuthenticated?: boolean;
        };
        CategoryResultDto: {
            /** Format: uuid */
            id?: string;
            category?: components["schemas"]["EvaluationCategory"];
            passed?: boolean;
            /** Format: int32 */
            points?: number | string;
            /** Format: int32 */
            maxPoints?: number | string;
            errorTip?: string;
            testCaseResults?: components["schemas"]["TestCaseResultDto"][];
        };
        CreateTaskCategoryDto: {
            name: string;
            /** Format: int32 */
            order?: number | string;
        };
        CreateTaskItemDto: {
            /** Format: uuid */
            taskCategoryId: string;
            title: string;
            description: string;
            difficulty?: components["schemas"]["Difficulty"];
            /** Format: int32 */
            order?: number | string;
            evaluationMode?: components["schemas"]["EvaluationMode"];
            expectedTypes?: components["schemas"]["ExpectedTypeInputDto"][];
            isVisible?: boolean;
            hints?: string[];
        };
        CreateTaskTestDto: {
            /** Format: uuid */
            taskItemId: string;
            input?: string;
            expectedOutput: string;
            description: string;
            /** Format: int32 */
            order?: number | string;
        };
        CreateTaskUnitTestFileDto: {
            /** Format: uuid */
            taskItemId: string;
            fileName: string;
            content: string;
            /** Format: int32 */
            order?: number | string;
            isVisibleToParticipant?: boolean;
        };
        /** @enum {unknown} */
        Difficulty: "Easy" | "Medium" | "Hard";
        /** @enum {unknown} */
        EvaluationCategory: "CharacterSet" | "NamingConventions" | "Compilability" | "CleanCode" | "TestCases" | "UnitTests" | "Functionality";
        /** @enum {unknown} */
        EvaluationMode: "ConsoleOnly" | "UnitTestOnly" | "Both";
        EvaluationResultDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            submissionId?: string;
            /** Format: int32 */
            totalScore?: number | string;
            /** Format: int32 */
            maxScore?: number | string;
            categoryResults?: components["schemas"]["CategoryResultDto"][];
        };
        ExpectedTypeInputDto: {
            name: string;
            methods?: string[];
        };
        /** Format: binary */
        IFormFile: string;
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
        SaveTaskCategoryWeightEntryDto: {
            category?: components["schemas"]["EvaluationCategory"];
            /** Format: double */
            weight?: number | string;
        };
        SaveTaskCategoryWeightsDto: {
            /** Format: uuid */
            taskItemId: string;
            weights?: components["schemas"]["SaveTaskCategoryWeightEntryDto"][];
        };
        SaveTaskTestEntryDto: {
            input?: string;
            expectedOutput: string;
            description: string;
            /** Format: int32 */
            order?: number | string;
        };
        SaveTaskTestsDto: {
            /** Format: uuid */
            taskItemId: string;
            tests?: components["schemas"]["SaveTaskTestEntryDto"][];
        };
        SaveTaskUnitTestFileEntryDto: {
            fileName: string;
            content: string;
            /** Format: int32 */
            order?: number | string;
            isVisibleToParticipant?: boolean;
        };
        SaveTaskUnitTestFilesDto: {
            /** Format: uuid */
            taskItemId: string;
            files?: components["schemas"]["SaveTaskUnitTestFileEntryDto"][];
        };
        SubmissionDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            taskItemId?: string;
            /** Format: date-time */
            submittedAt?: string;
            status?: components["schemas"]["SubmissionStatus"];
        };
        /** @enum {unknown} */
        SubmissionStatus: "Pending" | "Running" | "Done" | "Failed";
        SubmissionStatusDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            taskItemId?: string;
            status?: components["schemas"]["SubmissionStatus"];
            /** Format: date-time */
            submittedAt?: string;
            errorMessage?: string;
        };
        TaskCategoryDto: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** Format: int32 */
            order?: number | string;
            isVisible?: boolean;
            tasks?: components["schemas"]["TaskItemDto"][];
        };
        TaskCategoryWeightDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            taskItemId?: string;
            category?: components["schemas"]["EvaluationCategory"];
            /** Format: double */
            weight?: number | string;
        };
        TaskExpectedTypeDto: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** Format: int32 */
            order?: number | string;
            methods?: string[];
        };
        TaskHintDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            taskItemId?: string;
            content?: string;
            /** Format: int32 */
            order?: number | string;
        };
        TaskItemDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            taskCategoryId?: string;
            title?: string;
            description?: string;
            difficulty?: components["schemas"]["Difficulty"];
            /** Format: int32 */
            order?: number | string;
            isVisible?: boolean;
            evaluationMode?: components["schemas"]["EvaluationMode"];
            expectedTypes?: components["schemas"]["TaskExpectedTypeDto"][];
            hints?: components["schemas"]["TaskHintDto"][];
            visibleUnitTestFiles?: components["schemas"]["TaskUnitTestFileDto"][];
        };
        TaskTestDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            taskItemId?: string;
            input?: string;
            expectedOutput?: string;
            description?: string;
            /** Format: int32 */
            order?: number | string;
        };
        TaskUnitTestFileDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            taskItemId?: string;
            fileName?: string;
            content?: string;
            /** Format: int32 */
            order?: number | string;
            isVisibleToParticipant?: boolean;
        };
        TestCaseResultDto: {
            /** Format: uuid */
            id?: string;
            description?: string;
            input?: string;
            expectedOutput?: string;
            actualOutput?: string;
            passed?: boolean;
            /** Format: int32 */
            order?: number | string;
        };
        UpdateTaskCategoryDto: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: int32 */
            order?: number | string;
            isVisible?: boolean;
        };
        UpdateTaskItemDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            taskCategoryId: string;
            title: string;
            description: string;
            difficulty?: components["schemas"]["Difficulty"];
            /** Format: int32 */
            order?: number | string;
            isVisible?: boolean;
            evaluationMode?: components["schemas"]["EvaluationMode"];
            expectedTypes?: components["schemas"]["ExpectedTypeInputDto"][];
            hints?: string[];
        };
        UpdateTaskTestDto: {
            /** Format: uuid */
            id: string;
            input?: string;
            expectedOutput: string;
            description: string;
            /** Format: int32 */
            order?: number | string;
        };
        UpdateTaskUnitTestFileDto: {
            /** Format: uuid */
            id: string;
            fileName: string;
            content: string;
            /** Format: int32 */
            order?: number | string;
            isVisibleToParticipant?: boolean;
        };
        VisibilityStateDto: {
            isVisible?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
