<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>soopworkshop-backend-api</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SoopWorkshop.Backend.Application\SoopWorkshop.Backend.Application.csproj" />
    <ProjectReference Include="..\SoopWorkshop.Backend.Infrastructure\SoopWorkshop.Backend.Infrastructure.csproj" />
    <ProjectReference Include="..\SoopWorkshop.Shared\SoopWorkshop.Shared.csproj" />
  </ItemGroup>

</Project>
