// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SoopWorkshop.Backend.Infrastructure.Persistence;

#nullable disable

namespace SoopWorkshop.Backend.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SoopWorkshop.Backend.Domain.Entities.CategoryResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorTip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EvaluationResultId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxPoints")
                        .HasColumnType("integer");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationResultId");

                    b.ToTable("CategoryResults");
                });

            modelBuilder.Entity("SoopWorkshop.Backend.Domain.Entities.EvaluationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("MaxScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId")
                        .IsUnique();

                    b.ToTable("EvaluationResults");
                });

            modelBuilder.Entity("SoopWorkshop.Backend.Domain.Entities.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TaskItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaskItemId");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("SoopWorkshop.Backend.Domain.Entities.SubmissionFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId");

                    b.ToTable("SubmissionFiles");
                });

            modelBuilder.Entity("SoopWorkshop.Backend.Domain.Entities.TaskCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TaskCategories");
                });

            modelBuilder.Entity("SoopWorkshop.Backend.Domain.Entities.TaskHint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("TaskItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaskItemId");

                    b.ToTable("TaskHints");
                });

            modelBuilder.Entity("SoopWorkshop.Backend.Domain.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("TaskCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("TaskCategoryId");

                    b.ToTable("TaskItems");
                });

            modelBuilder.Entity("SoopWorkshop.Backend.Domain.Entities.TaskTest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ExpectedOutput")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("TaskItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaskItemId");

                    b.ToTable("TaskTests");
                });

            modelBuilder.Entity("SoopWorkshop.Backend.Domain.Entities.TestCaseResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActualOutput")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CategoryResultId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ExpectedOutput")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CategoryResultId");

                    b.ToTable("TestCaseResults");
                });

            modelBuilder.Entity("SoopWorkshop.Backend.Domain.Entities.CategoryResult", b =>
                {
                    b.HasOne("SoopWorkshop.Backend.Domain.Entities.EvaluationResult", "EvaluationResult")
                        .WithMany("CategoryResults")
                        .HasForeignKey("EvaluationResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EvaluationResult");
                });

            modelBuilder.Entity("SoopWorkshop.Backend.Domain.Entities.EvaluationResult", b =>
                {
                    b.HasOne("SoopWorkshop.Backend.Domain.Entities.Submission", "Submission")
                        .WithOne("EvaluationResult")
                        .HasForeignKey("SoopWorkshop.Backend.Domain.Entities.EvaluationResult", "SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("SoopWorkshop.Backend.Domain.Entities.Submission", b =>
                {
                    b.HasOne("SoopWorkshop.Backend.Domain.Entities.TaskItem", "Task")
                        .WithMany("Submissions")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("SoopWorkshop.Backend.Domain.Entities.SubmissionFile", b =>
                {
                    b.HasOne("SoopWorkshop.Backend.Domain.Entities.Submission", "Submission")
                        .WithMany("Files")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("SoopWorkshop.Backend.Domain.Entities.TaskHint", b =>
                {
                    b.HasOne("SoopWorkshop.Backend.Domain.Entities.TaskItem", "Task")
                        .WithMany("Hints")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("SoopWorkshop.Backend.Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("SoopWorkshop.Backend.Domain.Entities.TaskCategory", "Category")
                        .WithMany("Tasks")
                        .HasForeignKey("TaskCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SoopWorkshop.Backend.Domain.Entities.TaskTest", b =>
                {
                    b.HasOne("SoopWorkshop.Backend.Domain.Entities.TaskItem", "Task")
                        .WithMany("Tests")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("SoopWorkshop.Backend.Domain.Entities.TestCaseResult", b =>
                {
                    b.HasOne("SoopWorkshop.Backend.Domain.Entities.CategoryResult", "CategoryResult")
                        .WithMany("TestCaseResults")
                        .HasForeignKey("CategoryResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryResult");
                });

            modelBuilder.Entity("SoopWorkshop.Backend.Domain.Entities.CategoryResult", b =>
                {
                    b.Navigation("TestCaseResults");
                });

            modelBuilder.Entity("SoopWorkshop.Backend.Domain.Entities.EvaluationResult", b =>
                {
                    b.Navigation("CategoryResults");
                });

            modelBuilder.Entity("SoopWorkshop.Backend.Domain.Entities.Submission", b =>
                {
                    b.Navigation("EvaluationResult");

                    b.Navigation("Files");
                });

            modelBuilder.Entity("SoopWorkshop.Backend.Domain.Entities.TaskCategory", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("SoopWorkshop.Backend.Domain.Entities.TaskItem", b =>
                {
                    b.Navigation("Hints");

                    b.Navigation("Submissions");

                    b.Navigation("Tests");
                });
#pragma warning restore 612, 618
        }
    }
}
